name: terraform
description: https://github.com/champ-oss/action-terraform

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3 # https://github.com/actions/checkout/tags
    - uses: actions/setup-python@v4 # https://github.com/actions/setup-python/tags
      with:
        python-version: '3.11' # https://github.com/python/cpython/tags
    - uses: hashicorp/setup-terraform@v2 # https://github.com/hashicorp/setup-terraform/tags
      with:
        terraform_version: 1.3.6 # https://github.com/hashicorp/terraform/tags
        terraform_wrapper: false
    - uses: aws-actions/configure-aws-credentials@v1 # https://github.com/aws-actions/configure-aws-credentials/tags
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/github
        aws-region: us-east-1
    - run: pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
      shell: bash
    - run: python ${GITHUB_ACTION_PATH}/main.py
      shell: bash
