name: main
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # https://github.com/actions/checkout/releases
      - uses: actions/setup-python@v4 # https://github.com/actions/setup-python/releases
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: pytest
