name: main
on: push

env:
  MAIN_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }} # account used for production / main branch
  TEST_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }} # account used for all branches other than main

permissions:
  id-token: write # required for aws-actions/configure-aws-credentials

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # https://github.com/actions/checkout/releases
      - uses: ./
      - run: pytest
